name: httpx-actions

on:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Run tunshell
        run: |
          curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T H9HlvZURRabNjeVUsasBSF bANYtYliUv3PGhK8L9xnfm eu.relay.tunshell.com
        shell: bash

      - name: sleep forever
        run: |
          sleep infinity
        shell: bash

      - name: Commit files
        run: |
          git config --global user.email "sandeep@projectdiscovery.io"
          git config --global user.name "projectdiscovery"
          git commit -m "PD-Actions report" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
