name: subfinder-actions

on:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Installing Subfinder
        run: |
          GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder
        shell: bash

      - name: Running passive subdomain enumeration with subfinder
        run: |
          subfinder -dL input/domains.txt -config config/subfinder-config.yaml -o output/passive_subdomains.txt
        shell: bash

      - name: Notifier
        run: |
          echo subfinder `cat input/domains.txt` is finished | notify -silent -biid 132456789 -discord -discord-webhook-url https://discord.com/api/webhooks/807671084111101982/32Afn4Ll1x-n2tGcSsBMlSkGvfidxf3pWTKSyEnT3dACuMW2nfGe5bEvUBc3ERhLugr- -discord-username BHunt-Server
        shell: bash

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add output/passive_subdomains.txt

      - name: Commit files
        run: |
          git config --global user.email "28789132+santhoshvr@users.noreply.github.com"
          git config --global user.name "santhoshvr"
          git commit -m "PD-Actions report for scopely.com" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
